Fix ignore Issue (#81)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -171,7 +171,8 @@ runs:
       run: |
         if [ -f "${{ steps.reform_path.outputs.workingDirectory }}/infra/main.bicep" ]; then
           # Check if targetScope is set to 'subscription' or 'resourceGroup'. The sample sentence in bicep is: targetScope = 'subscription'
-          targetScope=$(grep -oP "targetScope\s*=\s*['\"]\K[^'\"]+" ${{ steps.reform_path.outputs.workingDirectory }}/infra/main.bicep)
+          targetScope=$(grep -oP "targetScope\s*=\s*['\"]\K[^'\"]+" "${{ steps.reform_path.outputs.workingDirectory }}/infra/main.bicep" 2>/dev/null || echo "")
+          echo "targetScope: $targetScope"
           echo "targetScope=$targetScope" >> $GITHUB_ENV
           if [ "$targetScope" == "subscription" ]; then
             echo "targetScope is set to 'subscription' in main.bicep"
@@ -179,10 +180,13 @@ runs:
           elif [ "$targetScope" == "resourceGroup" ]; then
             echo "targetScope is set to 'resourceGroup' in main.bicep"
           else
-            echo "targetScope is not set to 'subscription' or 'resourceGroup' in main.bicep"
+            echo "targetScope is not set to 'subscription' or 'resourceGroup' in main.bicep, set to 'resourceGroup' by default"
+            targetScope="resourceGroup"
+            echo "targetScope=$targetScope" >> $GITHUB_ENV
           fi
         fi
       shell: bash
+      continue-on-error: true
 
     - name: Set azure resource group name in env
       id: set_resource_group
@@ -401,6 +405,14 @@ runs:
       env:
         CREATE_ROLE_FOR_USER: false
         AZURE_PRINCIPAL_TYPE: "ServicePrincipal"
+
+    - name: Azure CLI script
+      id: delete_resource_group
+      if : ${{ inputs.validateAzd == 'true' && env.targetScope == 'resourceGroup' }}
+      run: |
+        az group delete --resource-group ${{ env.AZURE_RESOURCE_GROUP }} -y || echo "Warning: Failed to delete resource group ${AZURE_RESOURCE_GROUP}, continuing..."
+      shell: bash
+      continue-on-error: true
 
     - id: set_output
       run: |
