support customized inputs (#41)
* update action interface

* update validator argument list

* update action.yaml

* format: format with ruff

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,21 +1,30 @@
 name: 'Gallery Standard Validation'
 description: 'Validate the standard of the gallery'
 inputs:
-  repositoryURL:
-    description: 'The URL of the repository to validate'
-    required: false
-  branch:
-    description: 'The branch of the repository to validate'
-    required: false
-    default: 'main'
   workingDirectory:
     description: 'The path of target template to validate'
-    required: false
+    required: true
     default: '.'
-  runAzdUp:
-    description: 'Run azd up'
+  validatePaths:
+    description: 'Comma-separated list of paths to validate'
     required: false
+  topics:
+    description: 'Comma-separated list of topics to check'
+    required: false
+  validateAzd:
+    description: 'Run azd up and azd down for validation'
+    required: true
     default: 'true'
+  useDevContainer:
+    description: 'Use dev container for validation'
+    required: true
+    default: 'true'
+  securityAction:
+    description: 'Run security action validation'
+    required: true
+    default: ''
+    options:
+      - 'PSRule'
 outputs:
   resultFile:
     description: "A file path to a results file."
@@ -23,43 +32,32 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - name: Prepare repository
-      run: |
-        if [ "${{ inputs.repositoryURL }}" != "" ]; then
-          echo "Cloning the ${{ inputs.branch }} branch"
-          git clone --branch ${{ inputs.branch }} ${{ inputs.repositoryURL }} ${{ runner.temp }}/candidate-repo
-          echo "REPOSITORY_PATH=${{ runner.temp }}/candidate-repo" >> $GITHUB_ENV
-          repo_info=$(echo "${{ inputs.repositoryUrl }}" | sed 's|https://github.com/||')
-          echo "REPOSITORY_NAME=$repo_info" >> $GITHUB_ENV
-        elif [ -d "${{ inputs.workingDirectory }}" ]; then
-          echo "Using the provided repo path: ${{ inputs.workingDirectory }}"
-          repository_path=$(realpath "${{ inputs.workingDirectory }}")
-          echo "REPOSITORY_PATH=$repository_path" >> $GITHUB_ENV
-        fi
-      shell: bash
-
     - name: Check for .devcontainer config
       id: check_devcontainer
+      if : ${{ inputs.useDevContainer == 'true' }}
       run: |
-        if [ -f "${{ env.REPOSITORY_PATH }}/.devcontainer/devcontainer.json" ]; then
-          echo "USE_DEVCONTAINER=true" >> $GITHUB_ENV
-        else
-          echo "USE_DEVCONTAINER=false" >> $GITHUB_ENV
+        if [ ! -f "${{ inputs.workingDirectory }}/.devcontainer/devcontainer.json" ]; then
+          echo "Error: devcontainer config does not exist but useDevContainer is set to true."
+          exit 1
         fi
       shell: bash
         
     - name: Extract topics
       id: extract_repo_info
+      if: ${{ inputs.topics != '""' }}
       run: |
         repository_name=${{ env.REPOSITORY_NAME || github.repository }}
         topics_list=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/$repository_name/topics | jq -r '.names | join(",")')
-        echo "topics=\"$topics_list\"" >> $GITHUB_ENV
+        echo "TOPICS=\"$topics_list\"" >> $GITHUB_ENV
       shell: bash
       env:
         GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
+    
+    # TODO: check security with PSRule or msdo
 
     - name: Set environment name with timestamp
       id: set_env_name
+      if: ${{ inputs.validateAzd == 'true' }}
       run: |
         current_time=$(date +%m%d%H%M)
         azure_env_name="${{ env.AZURE_ENV_NAME }}-$current_time"
@@ -70,17 +68,17 @@ runs:
         AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
 
     - name: Copy validator into devcontainer
-      if: ${{ env.USE_DEVCONTAINER == 'true' }}
+      if: ${{ inputs.useDevContainer == 'true' }}
       run: |
-        mkdir -p ${{ env.REPOSITORY_PATH }}/tva_${{ github.run_id }}
-        cp -r ${{ github.action_path }}/src ${{ env.REPOSITORY_PATH }}/tva_${{ github.run_id }}/src
-        cp ${{ github.action_path }}/requirements.txt ${{ env.REPOSITORY_PATH }}/tva_${{ github.run_id }}/requirements.txt
-        env > ${{ env.REPOSITORY_PATH }}/tva_${{ github.run_id }}/env_variables.txt
+        mkdir -p ${{ inputs.workingDirectory }}/tva_${{ github.run_id }}
+        cp -r ${{ github.action_path }}/src ${{ inputs.workingDirectory }}/tva_${{ github.run_id }}/src
+        cp ${{ github.action_path }}/requirements.txt ${{ inputs.workingDirectory }}/tva_${{ github.run_id }}/requirements.txt
+        env > ${{ inputs.workingDirectory }}/tva_${{ github.run_id }}/env_variables.txt
       shell: bash
 
     - uses: actions/github-script@v6
       id: script
-      if: ${{ env.USE_DEVCONTAINER == 'true' }}
+      if: ${{ inputs.useDevContainer == 'true' && inputs.validateAzd == 'true' }}
       with:
         debug: true
         script: |
@@ -93,25 +91,25 @@ runs:
 
     # A workaround to those template that using Docker 
     - name: Start Docker
-      if: ${{ env.USE_DEVCONTAINER == 'true' }}
+      if: ${{ inputs.useDevContainer == 'true' && inputs.validateAzd == 'true' }}
       uses: devcontainers/ci@v0.3
       with:
         runCmd: |
           if find . -type f -iname 'dockerfile' | grep -q .; then
             sudo service docker start
           fi
-        subFolder: ${{ env.REPOSITORY_PATH }}
+        subFolder: ${{ inputs.workingDirectory }}
       continue-on-error: true
 
     - name: Login azd in devcontainer
       id: azd-login
-      if: ${{ env.USE_DEVCONTAINER == 'true' }}
+      if: ${{ inputs.useDevContainer == 'true' && inputs.validateAzd == 'true' }}
       uses: devcontainers/ci@v0.3
       with:
         runCmd: |
           azd auth login --client-id "${{ env.AZURE_CLIENT_ID }}" --federated-credential-provider "github" --tenant-id "${{ env.AZURE_TENANT_ID }}"
           az login --service-principal -u "${{ env.AZURE_CLIENT_ID }}" --federated-token $AZURE_AD_TOKEN --tenant "${{ env.AZURE_TENANT_ID }}"
-        subFolder: ${{ env.REPOSITORY_PATH }}
+        subFolder: ${{ inputs.workingDirectory }}
         env: |
           ACTIONS_ID_TOKEN_REQUEST_URL=${{ steps.script.outputs.ID_TOKEN_URL }}
           ACTIONS_ID_TOKEN_REQUEST_TOKEN=${{ steps.script.outputs.TOKEN }}
@@ -120,7 +118,7 @@ runs:
       
     - name: Setup Python in devcontainer
       id: setup-python
-      if: ${{ env.USE_DEVCONTAINER == 'true' }}
+      if: ${{ inputs.useDevContainer == 'true' }}
       uses: devcontainers/ci@v0.3
       with:
         runCmd: |
@@ -131,11 +129,22 @@ runs:
           python3 -m venv .venv --system-site-packages
           source .venv/bin/activate
           python3 -m pip install -r tva_${{ github.run_id }}/requirements.txt;
-        subFolder: ${{ env.REPOSITORY_PATH }}
+        subFolder: ${{ inputs.workingDirectory }}
     
+    - name: Remove spaces from inputs
+      id: remove_spaces
+      run: |
+        inputs_validatePaths="${{ inputs.validatePaths }}"
+        inputs_topics="${{ inputs.topics }}"
+        inputs_validatePaths=$(echo "$inputs_validatePaths" | sed 's/ //g')
+        inputs_topics=$(echo "$inputs_topics" | sed 's/ //g')
+        echo "validatePaths=$inputs_validatePaths" >> $GITHUB_ENV
+        echo "expected_topics=$inputs_topics" >> $GITHUB_ENV
+      shell: bash
+
     - name: Run validation
       id: validation
-      if: ${{ env.USE_DEVCONTAINER == 'true' }}
+      if: ${{ inputs.useDevContainer == 'true' }}
       uses: devcontainers/ci@v0.3
       with:
         runCmd: |
@@ -148,40 +157,40 @@ runs:
               fi
             done < tva_${{ github.run_id }}/env_variables.txt
           fi
-          if [ "${{ inputs.runAzdUp }}" = "true" ]; then
-            python3 tva_${{ github.run_id }}/src/gallery_validate.py . --output tva_${{ github.run_id }}/output.log --debug --topics $TOPICS --azdup --azddown
-          else
-            python3 tva_${{ github.run_id }}/src/gallery_validate.py . --output tva_${{ github.run_id }}/output.log --debug --topics $TOPICS
+          arguments="--topics ${{ env.TOPICS }}"
+          if [ -n "${{ env.expected_topics }}" ]; then
+            arguments+=" --expected_topics ${{ env.expected_topics }}"
           fi
-        subFolder: ${{ env.REPOSITORY_PATH }}
+          if [ "${{ inputs.validateAzd }}" = "true" ]; then
+            arguments+=" --validate_azd" 
+          fi
+          if [ -n "${{ env.validatePaths }}" ]; then
+            arguments+=" --validate_paths ${{ env.validatePaths }}"
+          fi
+          python3 tva_${{ github.run_id }}/src/gallery_validate.py . --output tva_${{ github.run_id }}/output.log $arguments
+        subFolder: ${{ inputs.workingDirectory }}
         env: |
           ACTIONS_ID_TOKEN_REQUEST_URL=${{ steps.script.outputs.ID_TOKEN_URL }}
           ACTIONS_ID_TOKEN_REQUEST_TOKEN=${{ steps.script.outputs.TOKEN }}
-          AZURE_CLIENT_ID=${{ env.AZURE_CLIENT_ID }}
-          AZURE_TENANT_ID=${{ env.AZURE_TENANT_ID }}
-          AZURE_ENV_NAME=${{ env.AZURE_ENV_NAME }}
-          AZURE_LOCATION=${{ env.AZURE_LOCATION }}
-          AZURE_SUBSCRIPTION_ID=${{ env.AZURE_SUBSCRIPTION_ID }}
           CREATE_ROLE_FOR_USER=false
           AZURE_PRINCIPAL_TYPE=ServicePrincipal
           FORCE_TERRAFORM_REMOTE_STATE_CREATION=false
-          TOPICS=${{ env.topics }}
     
     - name: Send output to main workflow
       id: send_output
-      if: ${{ env.USE_DEVCONTAINER == 'true' }}
+      if: ${{ inputs.useDevContainer == 'true' }}
       uses: devcontainers/ci@v0.3
       with:
         runCmd: |
           cat tva_${{ github.run_id }}/output.log
-        subFolder: ${{ env.REPOSITORY_PATH }}
+        subFolder: ${{ inputs.workingDirectory }}
 
     - name: Install AZD
-      if: ${{ env.USE_DEVCONTAINER == 'false' }}
+      if: ${{ inputs.useDevContainer == 'false' }}
       uses: Azure/setup-azd@v1.0.0
 
     - name: Log in with Azure (Federated Credentials)
-      if: ${{ env.AZURE_CLIENT_ID != '' && env.USE_DEVCONTAINER == 'false' }}
+      if: ${{ env.AZURE_CLIENT_ID != '' && inputs.useDevContainer == 'false' }}
       run: |
         azd auth login --client-id "${{ env.AZURE_CLIENT_ID }}" --federated-credential-provider "github" --tenant-id "${{ env.AZURE_TENANT_ID }}"
       shell: bash
@@ -191,18 +200,23 @@ runs:
 
     - name: Run validation
       id: run_validation
-      if: ${{ env.USE_DEVCONTAINER == 'false' }}
-      working-directory: ${{ env.REPOSITORY_PATH }}
+      if: ${{ inputs.useDevContainer == 'false' }}
+      working-directory: ${{ inputs.workingDirectory }}
       run: |
         pip install -r ${{ github.action_path }}/requirements.txt
-        if [ "${{ inputs.runAzdUp }}" = "true" ]; then
-          python ${{ github.action_path }}/src/gallery_validate.py . --debug --topics ${{ env.TOPICS }} --output ${{ env.AZURE_ENV_NAME }}-output.log --azdup --azddown
-        else
-          python ${{ github.action_path }}/src/gallery_validate.py . --debug --topics ${{ env.TOPICS }} --output ${{ env.AZURE_ENV_NAME }}-output.log
+        arguments='--topics ${{ env.TOPICS }}'
+        if [ -n "${{ env.expected_topics }}" ]; then
+          arguments+=" --expected_topics ${{ env.expected_topics }}"
         fi
+        if [ "${{ inputs.validateAzd }}" = "true" ]; then
+          arguments+=" --validate_azd" 
+        fi
+        if [ -n "${{ env.validatePaths }}" ]; then
+          arguments+=" --validate_paths ${{ env.validatePaths }}"
+        fi
+        python3 ${{ github.action_path }}/src/gallery_validate.py . --output ${{ env.AZURE_ENV_NAME }}-output.log $arguments
       shell: bash
       env:
-        TOPICS: ${{ env.topics }}
         AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
         AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
         AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
@@ -211,13 +225,13 @@ runs:
 
     - id: set_output
       run: |
-        if [[ ${{ env.USE_DEVCONTAINER }} == 'true' ]]; then
+        if [[ ${{ inputs.useDevContainer }} == 'true' ]]; then
           echo "${{ steps.send_output.outputs.runCmdOutput }}" >> ${{ env.AZURE_ENV_NAME }}-output.log
         fi
         output_link=$(realpath ${{ env.AZURE_ENV_NAME }}-output.log)
         echo "resultFile is $output_link"
         echo "resultFile=$output_link" >> $GITHUB_OUTPUT
-      working-directory: ${{ env.REPOSITORY_PATH }}
+      working-directory: ${{ inputs.workingDirectory }}
       shell: bash 
       env:
         AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
